class CfgPatches
{
	class SEP_Identities
	{
		author="Grave";
		addonRootClass="A3_Characters_F";
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_data_f",
			"A3_Characters_F",
			"A3_Characters_F_Beta",
			"A3_Characters_F_Bootcamp",
			"A3_Characters_F_Epa",
			"A3_Characters_F_Epb",
			"A3_Characters_F_Epc",
			"A3_Characters_F_Gamma",
			"A3_Characters_F_Aow",
			"A3_Characters_F_Exp",
			"A3_Characters_F_Oldman",
			"A3_Characters_F_Enoch",
			"A3_Characters_F_Jets",
			"A3_Characters_F_Mark",
			"A3_Characters_F_Orange",
			"A3_Characters_F_Tank"
		};
	};
};
class CfgFaces
{
	class Default
	{
		class Custom;
	};
	class Man_A3: Default
	{
		class Default;
		class SEP_Hispanic_01: Default
		{
			displayName="Morales";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_01_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_01.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_01_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_01_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_01_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_01_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_01.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_01.rvmat";
		};
		class SEP_Hispanic_02: Default
		{
			displayName="Perez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_02_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_02.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_02_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_02_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_02_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_02_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_02.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_02.rvmat";
		};
		class SEP_Hispanic_03: Default
		{
			displayName="Mendoza";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_03_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_03.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_03_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_03_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_03_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_03_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_03.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_03.rvmat";
		};
		class SEP_Hispanic_04: Default
		{
			displayName="Gonzalez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_04_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_04.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_04_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_04_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_04_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_04_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_04.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_04.rvmat";
		};
		class SEP_Hispanic_05: Default
		{
			displayName="Ruiz";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_05_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_05.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_05_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_05_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_05_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_05_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_05.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_05.rvmat";
		};
		class SEP_Hispanic_06: Default
		{
			displayName="Flores";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_06_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_06.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_06_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_06_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_06_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_06_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_06.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_06.rvmat";
		};
		class SEP_Hispanic_07: Default
		{
			displayName="Alvarado";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_07_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_07.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_07_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_07_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_07_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_07_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_07.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_07.rvmat";
		};
		class SEP_Hispanic_08: Default
		{
			displayName="Reyes";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_08_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_08.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_08_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_08_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_08_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_08_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_08.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_08.rvmat";
		};
		class SEP_Hispanic_09: Default
		{
			displayName="Velasquez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_09_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_09.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_09_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_09_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_09_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_09_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_09.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_09.rvmat";
		};
	};
};

class CfgWorlds
{
	class GenericNames
	{
		class HispanicMen
		{
			class FirstNames
			{
				juan="Juan";
				hector="Hector";
				gabriel="Gabriel";
				manuel="Manuel";
				orlando="Orlando";
				salvador="Salvador";
				roberto="Roberto";
				hugo="Hugo";
				santiago="Santiago";
				felipe="Felipe";
				diego="Diego";
				emmanuel="Emmanuel";
				julian="Julian";
				fernando="Fernando";
				jorge="Jorge";
				ricardo="Ricardo";
				raul="RaÃºl";
				mario="Mario";
				artuo="Artuo";
				gerardo="Gerardo";
				armando="Armando";
				oscar="Oscar";
				victor="Victor";
				elijah="Elijah";
				xavier="Xavier";
				isaac="Isaac";
				guillermo="Guillermo";
				ramon="Ramon";
				pablo="Pablo";
				francisco="Francisco";
				alfredo="Alfredo";
				antonio="Antonio";
				jose="Jose";
				sebastian="Sebastian";
				carlos="Carlos";
				eduardo="Eduardo";
			};
			class LastNames
			{
				gonzalez="Gonzalez";
				perez="Perez";
				garcia="Garcia";
				sanchez="Sanchez";
				diaz="Diaz";
				ramirez="Ramirez";
				fernandez="Fernandez";
				mendoza="Mendoza";
				moreno="Moreno";
				jimenez="Jimenez";
				alvarez="Alvarez";
				marquez="Marquez";
				flores="Flores";
				pena="Pena";
				morales="Morales";
				vargas="Vargas";
				parra="Parra";
				ramos="Ramos";
				velasquez="Velasquez";
				hernandez="Hernandez";
				mendez="Mendez";
				quintero="Quintero";
				guzman="Guzman";
			};
		};		
		
		class BrazilianMen
		{
			class FirstNames
			{
				adriano="Adriano";
				afonso="Afonso";
				benicio="Benicio";
				bento="Bento";
				bernardo="Bernardo";
				bruno="Bruno";
				caio="Caio";
				cristiano="Cristiano";
				damiao="Damiao";
				davi="Davi";
				diego="Diego";
				eduardo="Eduardo";
				emanuel="Emanuel";
				felipe="Felipe";
				flavio="Flavio";
				guilherme="Guilherme";
				gilberto="Gilberto";
				heitor="Heitor";
				henrique="Henrique";
				horacio="Horacio";
				joaquim="Joaquim";
				luciano="Luciano";
				mathues="Mathues";
				manuel="Manuel";
				osvaldo="Osvaldo";
				paco="Paco";
				rafael="Rafael";
				reginaldo="Reginaldo";
				renato="Renato";
				ricardo="Ricardo";
				roberto="Roberto";
				salvador="Salvador";
				santiago="Santiago";
				tiago="Tiago";
				vicente="Vicente";
				vitor="Vitor";
			};
			class LastNames
			{
				aldo="Aldo";
				almeida="Almeida";
				alvares="Alvarez";
				andrade="Andrade";
				batista="Batista";
				benites="Benites";
				caldeira="Caldeira";
				candido="Candido";
				cardosa="Cardosa";
				cesario="Cesario";
				diaz="Diaz";
				domingos="Domingos";
				fagundes="Fagundes";
				felicio="Felicio";
				gabriel="Gabriel";
				gimenes="Gimenes";
				henriques="Henriques";
				inacio="Inacio";
				madureira="Madureira";
				marques="Marques";
				moreira="Moreira";
				nunes="Nunes";
				oliveira="Oliveira";
				ortega="Ortega";
				pereira="Pereira";
				ramires="Ramires";
				ramos="Ramos";
				santana="Santana";
				senna="Senna";
				silva="Silva";
				torres="Torres";
				vargas="Vargas";
			};
		};
	};
};