class CfgPatches
{
	class SEP_Identities
	{
		author="Joe";
		addonRootClass="A3_Characters_F";
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_data_f",
			"A3_Characters_F",
			"A3_Characters_F_Beta",
			"A3_Characters_F_Bootcamp",
			"A3_Characters_F_Epa",
			"A3_Characters_F_Epb",
			"A3_Characters_F_Epc",
			"A3_Characters_F_Gamma",
			"A3_Characters_F_Aow",
			"A3_Characters_F_Exp",
			"A3_Characters_F_Oldman",
			"A3_Characters_F_Enoch",
			"A3_Characters_F_Jets",
			"A3_Characters_F_Mark",
			"A3_Characters_F_Orange",
			"A3_Characters_F_Tank"
		};
	};
};
class CfgFaces
{
	class Default
	{
		class Custom;
	};
	class Man_A3: Default
	{
		class Default;
		class PersianHead_A3_01;
		//Hispanic//
		class SEP_Hispanic_01: Default
		{
			displayName="Morales";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_01_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_01.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_01_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_01_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_01_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_01_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_01.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_01.rvmat";
		};
		class SEP_Hispanic_02: Default
		{
			displayName="Perez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_02_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_02.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_02_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_02_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_02_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_02_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_02.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_02.rvmat";
		};
		class SEP_Hispanic_03: Default
		{
			displayName="Mendoza";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_03_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_03.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_03_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_03_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_03_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_03_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_03.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_03.rvmat";
		};
		class SEP_Hispanic_04: Default
		{
			displayName="Gonzalez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_04_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_04.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_04_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_04_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_04_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_04_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_04.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_04.rvmat";
		};
		class SEP_Hispanic_05: Default
		{
			displayName="Ruiz";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_05_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_05.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_05_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_05_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_05_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_05_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_05.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_05.rvmat";
		};
		class SEP_Hispanic_06: Default
		{
			displayName="Flores";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_06_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_06.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_06_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_06_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_06_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_06_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_06.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_06.rvmat";
		};
		class SEP_Hispanic_07: Default
		{
			displayName="Alvarado";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_07_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_07.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_07_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_07_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_07_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_07_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_07.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_07.rvmat";
		};
		class SEP_Hispanic_08: Default
		{
			displayName="Reyes";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_08_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_08.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_08_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_08_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_08_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_08_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_08.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_08.rvmat";
		};
		class SEP_Hispanic_09: Default
		{
			displayName="Velasquez";
			author="Grave";
			identityTypes[]=
			{
				"Head_Hispanic"
			};
			head="NATOHead_A3";
			texture="SEP_Identities\Data\Head_Hispanic_09_CO.paa";
			material="SEP_Identities\Data\Head_Hispanic_09.rvmat";
			materialWounded1="SEP_Identities\Data\Head_Hispanic_09_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\Head_Hispanic_09_Injury.rvmat";
			textureHL="SEP_Identities\Data\Body_Hispanic_09_CO.paa";
			textureHL2="SEP_Identities\Data\Body_Hispanic_09_CO.paa";
			materialHL="SEP_Identities\Data\Body_Hispanic_09.rvmat";
			materialHL2="SEP_Identities\Data\Body_Hispanic_09.rvmat";
		};
		
		//Sikh//
		class SEP_Sikh_01: PersianHead_A3_01
		{
			displayName="Ajit";
			author="Joe";
			identityTypes[]=
			{
				"Head_Sikh"
			};
			head = "PersianHead_A3";
			texture="SEP_Identities\Data\sikh\Head_Sikh_01_CO.paa";
			material="SEP_Identities\Data\sikh\Head_Sikh_01.rvmat";
			materialWounded1="SEP_Identities\Data\sikh\Head_Sikh_01_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\sikh\Head_Sikh_01_Injury.rvmat";
			textureHL="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			textureHL2="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			materialHL="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
			materialHL2="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
		};
		class SEP_Sikh_02: Default
		{
			displayName="Ekam";
			author="Joe";
			identityTypes[]=
			{
				"Head_Sikh"
			};
			head = "PersianHead_A3";
			texture="SEP_Identities\Data\sikh\Head_Sikh_02_CO.paa";
			material="SEP_Identities\Data\sikh\Head_Sikh_02.rvmat";
			materialWounded1="SEP_Identities\Data\sikh\Head_Sikh_02_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\sikh\Head_Sikh_02_Injury.rvmat";
			textureHL="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			textureHL2="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			materialHL="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
			materialHL2="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
		};
		class SEP_Sikh_03: PersianHead_A3_01
		{
			displayName="Guneet";
			author="Joe";
			identityTypes[]=
			{
				"Head_Sikh"
			};
			head = "TanoanHead_A3";
			texture="SEP_Identities\Data\sikh\Head_Sikh_03_CO.paa";
			material="SEP_Identities\Data\sikh\Head_Sikh_03.rvmat";
			materialWounded1="SEP_Identities\Data\sikh\Head_Sikh_03_Injury.rvmat";
			materialWounded2="SEP_Identities\Data\sikh\Head_Sikh_03_Injury.rvmat";
			textureHL="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			textureHL2="SEP_Identities\Data\sikh\Body_Sikh_03_CO.paa";
			materialHL="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
			materialHL2="SEP_Identities\Data\sikh\Body_Sikh_03.rvmat";
		};		
	};
};

class CfgWorlds
{
	class GenericNames
	{
		class HispanicMen
		{
			class FirstNames
			{
				juan="Juan";
				hector="Hector";
				gabriel="Gabriel";
				manuel="Manuel";
				orlando="Orlando";
				salvador="Salvador";
				roberto="Roberto";
				hugo="Hugo";
				santiago="Santiago";
				felipe="Felipe";
				diego="Diego";
				emmanuel="Emmanuel";
				julian="Julian";
				fernando="Fernando";
				jorge="Jorge";
				ricardo="Ricardo";
				raul="RaÃºl";
				mario="Mario";
				artuo="Artuo";
				gerardo="Gerardo";
				armando="Armando";
				oscar="Oscar";
				victor="Victor";
				elijah="Elijah";
				xavier="Xavier";
				isaac="Isaac";
				guillermo="Guillermo";
				ramon="Ramon";
				pablo="Pablo";
				francisco="Francisco";
				alfredo="Alfredo";
				antonio="Antonio";
				jose="Jose";
				sebastian="Sebastian";
				carlos="Carlos";
				eduardo="Eduardo";
			};
			class LastNames
			{
				gonzalez="Gonzalez";
				perez="Perez";
				garcia="Garcia";
				sanchez="Sanchez";
				diaz="Diaz";
				ramirez="Ramirez";
				fernandez="Fernandez";
				mendoza="Mendoza";
				moreno="Moreno";
				jimenez="Jimenez";
				alvarez="Alvarez";
				marquez="Marquez";
				flores="Flores";
				pena="Pena";
				morales="Morales";
				vargas="Vargas";
				parra="Parra";
				ramos="Ramos";
				velasquez="Velasquez";
				hernandez="Hernandez";
				mendez="Mendez";
				quintero="Quintero";
				guzman="Guzman";
			};
		};		
		
		class BrazilianMen
		{
			class FirstNames
			{
				adriano="Adriano";
				afonso="Afonso";
				benicio="Benicio";
				bento="Bento";
				bernardo="Bernardo";
				bruno="Bruno";
				caio="Caio";
				cristiano="Cristiano";
				damiao="Damiao";
				davi="Davi";
				diego="Diego";
				eduardo="Eduardo";
				emanuel="Emanuel";
				felipe="Felipe";
				flavio="Flavio";
				guilherme="Guilherme";
				gilberto="Gilberto";
				heitor="Heitor";
				henrique="Henrique";
				horacio="Horacio";
				joaquim="Joaquim";
				luciano="Luciano";
				mathues="Mathues";
				manuel="Manuel";
				osvaldo="Osvaldo";
				paco="Paco";
				rafael="Rafael";
				reginaldo="Reginaldo";
				renato="Renato";
				ricardo="Ricardo";
				roberto="Roberto";
				salvador="Salvador";
				santiago="Santiago";
				tiago="Tiago";
				vicente="Vicente";
				vitor="Vitor";
			};
			class LastNames
			{
				aldo="Aldo";
				almeida="Almeida";
				alvares="Alvarez";
				andrade="Andrade";
				batista="Batista";
				benites="Benites";
				caldeira="Caldeira";
				candido="Candido";
				cardosa="Cardosa";
				cesario="Cesario";
				diaz="Diaz";
				domingos="Domingos";
				fagundes="Fagundes";
				felicio="Felicio";
				gabriel="Gabriel";
				gimenes="Gimenes";
				henriques="Henriques";
				inacio="Inacio";
				madureira="Madureira";
				marques="Marques";
				moreira="Moreira";
				nunes="Nunes";
				oliveira="Oliveira";
				ortega="Ortega";
				pereira="Pereira";
				ramires="Ramires";
				ramos="Ramos";
				santana="Santana";
				senna="Senna";
				silva="Silva";
				torres="Torres";
				vargas="Vargas";
			};
		};

		class RomanianMen
		{
			class FirstNames
			{
				adrian="Adrian";
				alexandru="Alexandru";
				alin="Alin";
				andrei="Andrei";
				angel="Angel";
				anton="Anton";
				bogdan="Bogdan";
				catalin="Catalin";
				ciprian="Ciprian";
				claudiu="Claudiu";
				constantin="Constantin";
				cornel="Cornel";
				cristian="Cristian";
				dan="Dan";
				daniel="Daniel";
				darius="Darius";
				dorin="Dorin";
				dragos="Dragos";
				eduard="Eduard";
				emil="Emil";
				florin="Florin";
				gavril="Gavril";
				george="George";
				horatiu="Horatiu";
				ilie="Ilie";
				ioan="Ioan";
				ion="Ion";
				ionel="Ionel";
				iulian="Iulian";
				laurentiu="Laurentiu";
				lucian="Lucian";
				marian="Marian";
				mihai="Mihai";
				nicu="Nicu";
				ovidiu="Ovidiu";
				sabin="Sabin";
			};
			class LastNames
			{
				albulescu="Albulescu";
				andronescu="Andronescu";
				anghel="Anghel";
				antonesei="Antonesei";
				apostol="Apostol";
				armean="Armean";
				avram="Avram";
				barbu="Barbu";
				bejan="Bejan";
				boeru="Boeru";
				bratu="Bratu";
				burcea="Burcea";
				calin="Calin";
				carp="Carp";
				chirila="Chirila";
				ciobanu="Ciobanu";
				constantinescu="Constantinescu";
				cornea="Cornea";
				cristea="Cristea";
				damian="Damian";
				dima="Dima";
				dobrescu="Dobrescu";
				dogaru="Dogaru";
				dumitrescu="Dumitrescu";
				ene="Ene";
				filip="Filip";
				florea="Florea";
				georgescu="Georgescu";
				ionescu="Ionescu";
				lazar="Lazar";
				marin="Marin";
				mihailescu="Mihailescu";
				moldovan="Moldovan";
				neagu="Neagu";
				petrescu="Petrescu";
				popescu="Popescu";
			};
		};
		
		class ItalianMen
		{
			class FirstNames
			{
				adriano="Adriano";
				alberto="Alberto";
				alessandro="Alessandro";
				alfio="Alfio";
				andrea="Andrea";
				angelo="Angelo";
				antonio="Antonio";
				armando="Armando";
				bruno="Bruno";
				carlo="Carlo";
				cataldo="Cataldo";
				claudio="Claudio";
				cornelio="Cornelio";
				costantino="Costantino";
				daniele="Daniele";
				domenico="Domenico";
				edoardo="Edoardo";
				efisio="Efisio";
				elia="Elia";
				enrico="Enrico";
				francesco="Francesco";
				gabriele="Gabriele";
				giannino="Giannino";
				gino="Gino";
				giorgio="Giorgio";
				giovanni="Giovanni";
				giuseppe="Giuseppe";
				giuliano="Giuliano";
				leone="Leone";
				lorenzo="Lorenzo";
				luciano="Luciano";
				marcello="Marcello";
				michele="Michele";
				nicola="Nicola";
				orazio="Orazio";
				paolo="Paolo";
				pietro="Pietro";
				raffaele="Raffaele";
				renato="Renato";
				ruggero="Ruggero";
				salvatore="Salvatore";
				sebastiano="Sebastiano";
				sergio="Sergio";
				silvano="Silvano";
				umberto="Umberto";
				vittorio="Vittorio";
			};
			class LastNames
			{
				barbieri="Barbieri";
				bellini="Bellini";
				bianchi="Bianchi";
				brambilla="Brambilla";
				caruso="Caruso";
				colombo="Colombo";
				conte="Conte";
				coppola="Coppola";
				deangelis="DeAngelis";
				degregorio="DeGregorio";
				esposito="Esposito";
				farina="Farina";
				ferrari="Ferrari";
				fontana="Fontana";
				gallo="Gallo";
				gentile="Gentile";
				grassi="Grassi";
				greco="Greco";
				lombardi="Lombardi";
				mancini="Mancini";
				marina="Marino";
				martini="Martini";
				melis="Melis";
				moretti="Moretti";
				orciani="Orciani";
				parisi="Parisi";
				pellegrini="Pellegrini";
				piras="Piras";
				ricci="Ricci";
				romano="Romano";
				rossi="Rossi";
				russo="Russo";
				santoro="Santoro";
				sartori="Sartori";
				serra="Serra";
				silvestri="Silvestri";
				testa="Testa";
				todaro="Todaro";
				toscano="Toscano";
				venturi="Venturi";
				vitali="Vitali";
				zaccaria="Zaccaria";
				zamboni="Zamboni";
				zappia="Zappia";
				zucca="Zucca";
			};
		};	

		class SikhMen
		{
			class FirstNames
			{
				amarjit="Amarjit";
				amritpal="Amritpal";
				baldev="Baldev";
				baljit="Baljit";
				balwinder="Balwinder";
				charanjit="Charanjit";
				daljit="Daljit";
				darshan="Darshan";
				gagandeep="Gagandeep";
				gurbachan="Gurbachan";
				gurcharan="Gurcharan";
				gurdeep="Gurdeep";
				gurdial="Gurdial";
				gurinder="Gurinder";
				gurjit="Gurjit";
				gurmukh="Gurmukh";
				gurpreet="Gurpreet";
				gursewak="Gursewak";
				harbhajan="Harbhajan";
				harinder="Harinder";
				harjit="Harjit";
				harpreet="Harpreet";
				hardeep="Hardeep";
				jagdeep="Jagdeep";
				jagjit="Jagjit";
				jasbir="Jasbir";
				jasdeep="Jasdeep";
				jaspreet="Jaspreet";
				kuldeep="Kuldeep";
				maninder="Maninder";
				manpreet="Manpreet";
				navdeep="Navdeep";
				parminder="Parminder";
				ranjit="Ranjit";
				sukhdeep="Sukhdeep";
			};
			class LastNames
			{				
				atwal="Atwal";
				bains="Bains";
				bajwa="Bajwa";
				bal="Bal";
				banga="Banga";
				basra="Basra";
				bath="Bath";
				bhatti="Bhatti";
				brar="Brar";
				cheema="Cheema";
				chahal="Chahal";
				deol="Deol";
				dhaliwal="Dhaliwal";
				dhillon="Dhillon";
				gill="Gill";
				gillan="Gillan";
				grewal="Grewal";
				hayer="Hayer";
				johal="Johal";
				kang="Kang";
				mann="Mann";
				matharu="Matharu";
				pannu="Pannu";
				randhawa="Randhawa";
				sahota="Sahota";
				sandhu="Sandhu";
				sehgal="Sehgal";
				shergill="Shergill";
				sidhu="Sidhu";
				sohi="Sohi";
				takhar="Takhar";
				thind="Thind";
				toor="Toor";
				uppal="Uppal";
				virk="Virk";
			};
		};	
	};
};